"""Render the Hysteria2 server config (YAML written by hand, no PyYAML)."""
from __future__ import annotations

import state as st


def _yaml(lines: list[str]) -> str:
    return "\n".join(lines) + "\n"


def build(data: dict) -> str | None:
    ib = st.get_type(data, "hysteria2")
    if not ib:
        return None
    port = ib.get("port", 443)
    socks_port = ib["socks_port"]
    lines = [
        "# Generated by xvei - do not edit by hand.",
        f"listen: :{port}",
        "",
    ]
    # lib/hysteria2.sh copies the active cert/key here so the (non-root)
    # hysteria-server service user can read them; refreshed by the renew hook.
    lines += [
        "tls:",
        "  cert: /etc/hysteria/cert.crt",
        "  key: /etc/hysteria/cert.key",
        "",
    ]
    lines += [
        "auth:",
        "  type: password",
        f"  password: {ib['password']}",
        "",
        "outbounds:",
        "  - name: xray",
        "    type: socks5",
        "    socks5:",
        f"      addr: 127.0.0.1:{socks_port}",
        "",
        "masquerade:",
        "  type: proxy",
        "  proxy:",
        "    url: https://news.ycombinator.com/",
        "    rewriteHost: true",
    ]
    up = ib.get("up_mbps") or 0
    down = ib.get("down_mbps") or 0
    if up or down:
        lines += ["", "bandwidth:", f"  up: {up} mbps", f"  down: {down} mbps"]
    return _yaml(lines)
