"""Client share links and full client configs, from config.json.

Xray inbounds get their links from rawlinks (read off the inbound itself);
Hysteria2 and Turnable, which run outside Xray, from the xvei state.
"""
from __future__ import annotations

import os
from urllib.parse import quote, urlencode

import proxylinks
import rawlinks
import routing
import state as st
import util
import xrayconf as xc

# local port the Turnable client listens on (`turnable client -l 127.0.0.1:1080`)
TURNABLE_CLIENT_PORT = 1080
# see lib/turnable.sh
TURNABLE_BIN = "/usr/local/bin/turnable"
TURNABLE_CONFIG = "/etc/turnable/config.json"


def _turnable_link(rec: dict) -> str:
    """The turnable:// link, generated by Turnable itself from its config."""
    uuid = rec.get("turnable_uuid")
    if not uuid or not os.path.exists(TURNABLE_BIN) or not os.path.exists(TURNABLE_CONFIG):
        return ""
    try:
        out = util.run([TURNABLE_BIN, "config", "generate", "xvei", uuid, "xray",
                        "-c", TURNABLE_CONFIG], check=False).stdout or ""
    except OSError:
        return ""
    for line in out.splitlines():
        if line.startswith("turnable://"):
            return f"{line.split('#', 1)[0]}#{rec['tag']}"
    return ""


def turnable_app_link(ib: dict) -> str:
    """The VLESS link for the proxy app, pointed at the local Turnable client."""
    clients = (ib.get("settings") or {}).get("clients") or [{}]
    label = quote(f"{ib['tag']}-local")
    q = {"encryption": "none", "security": "none", "type": "tcp"}
    return f"vless://{clients[0].get('id', '')}@127.0.0.1:{TURNABLE_CLIENT_PORT}?{urlencode(q)}#{label}"


def _hysteria2_link(data: dict, rec: dict) -> str:
    domain = data.get("domain") or ""
    q = {"sni": domain}
    if data.get("cert", {}).get("mode") != "letsencrypt":
        q["insecure"] = "1"
    label = quote(f"{rec['tag']}@{domain or data.get('server_ip') or 'xvei'}")
    return (f"hysteria2://{quote(rec['password'])}@{rawlinks.host_for(data)}:"
            f"{rec.get('port', 443)}/?{urlencode(q)}#{label}")


def inbound_links(data: dict, cfg: dict, tag: str) -> list[tuple[str, str]] | None:
    """[(client name, link)] of an inbound; None if there is no such inbound."""
    ib = xc.find_inbound(cfg, tag)
    if ib is None:
        return None
    hy = st.service(data, cfg, "hysteria2")
    if hy and hy["tag"] == tag:
        return [("", _hysteria2_link(data, hy))]
    tu = st.service(data, cfg, "turnable")
    if tu and tu["tag"] == tag:
        link = _turnable_link(tu)
        return [("", link)] if link else []
    return rawlinks.inbound_links(data, cfg, ib)[0]


def _note(data: dict, cfg: dict, ib: dict) -> str:
    return rawlinks.inbound_links(data, cfg, ib)[1]


def _detail(data: dict, ib: dict) -> str:
    own = st.owned_type(data, ib.get("tag", ""))
    return f"{own} {util.SYM['sep']} " + xc.inbound_detail(ib) if own else xc.inbound_detail(ib)


def _inbound_title(tag: str, detail: str) -> None:
    print(f"\n{util.paint(tag, util.BOLD, util.CYAN)}  {util.paint(detail, util.DIM)}")


def _client(name: str, link: str) -> None:
    """A client name, then its link alone on a line (so it copies cleanly)."""
    if name:
        print(f"  {util.paint(util.SYM['dot'] + ' ' + name, util.YELLOW)}")
    print(link)


def print_links(data: dict, cfg: dict, tag: str | None = None) -> None:
    util.header("Client links")
    shown = False
    for ib in xc.inbounds(cfg):
        t = ib.get("tag")
        if not t or (tag and t != tag):
            continue
        shown = True
        _inbound_title(t, _detail(data, ib))
        tu = st.service(data, cfg, "turnable")
        if tu and tu["tag"] == t:
            link = _turnable_link(tu)
            _client("1. Turnable client, run on the device:",
                    f"turnable client -l 127.0.0.1:{TURNABLE_CLIENT_PORT} "
                    f"'{link or '<not available: Turnable is not installed>'}'")
            print()
            _client("2. Proxy app (v2rayNG, NekoBox, ...), import:", turnable_app_link(ib))
            continue
        found = inbound_links(data, cfg, t) or []
        if not found:
            print(util.paint(f"  no link: {_note(data, cfg, ib) or 'unknown'}", util.DIM))
        for i, (name, link) in enumerate(found):
            if i:
                print()
            _client(name if len(found) > 1 else "", link)
    if not shown:
        print(util.paint("  (no inbounds)", util.DIM))
    print(util.paint("\nQR code: xvei qr <tag> [client]   (menu: Links / QR codes)", util.DIM))


# ---- full client config (Xray core format) ------------------------------

def full_config(cfg: dict, link: str) -> dict:
    """A complete Xray client config around one share link."""
    # Local split-tunneling on the CLIENT's own device: "direct" here means
    # "use my own ISP connection, skip the VPS" -- it never touches the
    # server, so it carries none of the server-side IP-exposure risk the
    # country templates guard against.
    rules: list[dict] = [
        {"type": "field", "outboundTag": "direct", "ip": ["geoip:private"]},
    ]
    template = routing.detect(cfg)["template"]
    if template in routing.COUNTRY_MATCHERS:
        dom, ips = routing.COUNTRY_MATCHERS[template]
        if dom:
            rules.append({"type": "field", "outboundTag": "direct", "domain": dom})
        if ips:
            rules.append({"type": "field", "outboundTag": "direct", "ip": ips})
    elif template == "popular":
        rules.append({"type": "field", "outboundTag": "direct",
                      "domain": list(routing.POPULAR_DOMAINS)})
    proxy, _name = proxylinks.parse(link)
    return {
        "log": {"loglevel": "warning"},
        "inbounds": [
            {"tag": "socks", "port": 10808, "listen": "127.0.0.1", "protocol": "socks",
             "settings": {"udp": True}},
            {"tag": "http", "port": 10809, "listen": "127.0.0.1", "protocol": "http"},
        ],
        "outbounds": [
            {"tag": "proxy", **proxy},
            {"protocol": "freedom", "tag": "direct"},
            {"protocol": "blackhole", "tag": "block"},
        ],
        "routing": {"domainStrategy": "IPIfNonMatch", "rules": rules},
    }
