"""Generate client share links + full client configs from state."""
from __future__ import annotations

import base64
import json
import os
from urllib.parse import quote, unquote, urlencode

import routing
import state as st
import util

# local port the Turnable client listens on (`turnable client -l 127.0.0.1:1080`)
TURNABLE_CLIENT_PORT = 1080
# see lib/turnable.sh
TURNABLE_BIN = "/usr/local/bin/turnable"
TURNABLE_CONFIG = "/etc/turnable/config.json"


def _turnable_link(ib: dict) -> str:
    """The turnable:// link, generated by Turnable itself from its config."""
    uuid = ib.get("turnable_uuid")
    if not uuid or not os.path.exists(TURNABLE_BIN) or not os.path.exists(TURNABLE_CONFIG):
        return ""
    try:
        out = util.run([TURNABLE_BIN, "config", "generate", "xvei", uuid, "xray",
                        "-c", TURNABLE_CONFIG], check=False).stdout or ""
    except OSError:
        return ""
    for line in out.splitlines():
        if line.startswith("turnable://"):
            return f"{line.split('#', 1)[0]}#{ib['tag']}"
    return ""


def turnable_app_link(data: dict, ib: dict) -> str:
    """The VLESS link for the proxy app, pointed at the local Turnable client."""
    label = quote(f"{ib['tag']}-local")
    q = {"encryption": "none", "security": "none", "type": "tcp"}
    return f"vless://{ib['uuid']}@127.0.0.1:{TURNABLE_CLIENT_PORT}?{urlencode(q)}#{label}"


def _endpoint_host(data: dict, ib: dict) -> str:
    # REALITY has no cert -> connect by IP; everything else by domain when present.
    if ib["type"] == "vless-xhttp-reality" or not data.get("domain"):
        return data.get("server_ip") or data.get("domain") or "SERVER_IP"
    return data["domain"]


def share_link(data: dict, ib: dict) -> str:
    label = quote(f"{ib['tag']}@{data.get('domain') or data.get('server_ip') or 'xvei'}")
    host = _endpoint_host(data, ib)
    domain = data.get("domain") or host
    t = ib["type"]

    if t == "vless-tls":
        q = {"encryption": "none", "security": "tls", "sni": domain, "fp": "chrome",
             "type": "tcp", "flow": "xtls-rprx-vision"}
        return f"vless://{ib['uuid']}@{host}:{ib.get('port', 443)}?{urlencode(q)}#{label}"

    if t == "vless-ws":
        q = {"encryption": "none", "security": "tls", "sni": domain, "fp": "chrome",
             "type": "ws", "host": domain, "path": "/" + ib["ws_path"]}
        return f"vless://{ib['uuid']}@{host}:443?{urlencode(q)}#{label}"

    if t == "vless-xhttp-reality":
        q = {"encryption": "none", "security": "reality", "sni": ib["server_names"][0],
             "fp": "chrome", "pbk": ib["public_key"], "sid": ib["short_ids"][0],
             "type": "xhttp", "path": "/" + ib["xhttp_path"], "mode": "auto"}
        return f"vless://{ib['uuid']}@{host}:{ib['port']}?{urlencode(q)}#{label}"

    if t == "vless-xhttp-tls":
        port = ib.get("port", 443) if ib.get("standalone") else 443
        q = {"encryption": "none", "security": "tls", "sni": domain, "fp": "chrome",
             "type": "xhttp", "host": domain, "path": "/" + ib["xhttp_path"], "mode": "auto"}
        return f"vless://{ib['uuid']}@{host}:{port}?{urlencode(q)}#{label}"

    # Trojan clients must negotiate http/1.1: on :443 an h2 connection is
    # handed to the camouflage site (see inbounds._vless_tls).
    if t == "trojan-tcp":
        q = {"security": "tls", "sni": domain, "fp": "chrome", "type": "tcp",
             "alpn": "http/1.1"}
        return f"trojan://{quote(ib['password'], safe='')}@{host}:443?{urlencode(q)}#{label}"

    if t == "trojan-ws":
        q = {"security": "tls", "sni": domain, "fp": "chrome", "type": "ws",
             "host": domain, "path": "/" + ib["ws_path"], "alpn": "http/1.1"}
        return f"trojan://{quote(ib['password'], safe='')}@{host}:443?{urlencode(q)}#{label}"

    if t == "vmess-ws":
        # v2rayN format: base64 of a JSON object
        j = {"v": "2", "ps": unquote(label), "add": host, "port": "443", "id": ib["uuid"],
             "aid": "0", "scy": "auto", "net": "ws", "type": "none", "host": domain,
             "path": "/" + ib["ws_path"], "tls": "tls", "sni": domain,
             "alpn": "http/1.1", "fp": "chrome"}
        return "vmess://" + base64.b64encode(json.dumps(j).encode()).decode()

    if t == "shadowsocks":
        userinfo = base64.urlsafe_b64encode(
            f"{ib['method']}:{ib['password']}".encode()).decode().rstrip("=")
        return f"ss://{userinfo}@{host}:{ib['port']}#{label}"

    if t == "turnable":
        return _turnable_link(ib)

    if t == "hysteria2":
        q = {"sni": domain}
        if data.get("cert", {}).get("mode") != "letsencrypt":
            q["insecure"] = "1"
        return f"hysteria2://{quote(ib['password'])}@{host}:{ib.get('port', 443)}/?{urlencode(q)}#{label}"

    return ""


# ---- full client config (Xray core format) ------------------------------

def _client_outbound(data: dict, ib: dict) -> dict:
    host = _endpoint_host(data, ib)
    domain = data.get("domain") or host
    t = ib["type"]
    if t == "shadowsocks":
        return {"protocol": "shadowsocks", "tag": "proxy",
                "settings": {"servers": [{"address": host, "port": ib["port"],
                                          "method": ib["method"], "password": ib["password"]}]}}
    if t == "turnable":
        return {"protocol": "vless", "tag": "proxy",
                "settings": {"vnext": [{"address": "127.0.0.1", "port": TURNABLE_CLIENT_PORT,
                                        "users": [{"id": ib["uuid"], "encryption": "none"}]}]},
                "streamSettings": {"network": "tcp", "security": "none"}}
    if t in ("trojan-tcp", "trojan-ws", "vmess-ws"):
        stream = {"network": "tcp" if t == "trojan-tcp" else "ws", "security": "tls",
                  "tlsSettings": {"serverName": domain, "fingerprint": "chrome",
                                  "alpn": ["http/1.1"]}}
        if t != "trojan-tcp":
            stream["wsSettings"] = {"path": "/" + ib["ws_path"], "host": domain}
        if t == "vmess-ws":
            settings = {"vnext": [{"address": host, "port": 443,
                                   "users": [{"id": ib["uuid"], "security": "auto"}]}]}
        else:
            settings = {"servers": [{"address": host, "port": 443, "password": ib["password"]}]}
        return {"protocol": "vmess" if t == "vmess-ws" else "trojan", "tag": "proxy",
                "settings": settings, "streamSettings": stream}
    # vless family
    user = {"id": ib["uuid"], "encryption": "none"}
    stream: dict = {}
    if t == "vless-tls":
        user["flow"] = "xtls-rprx-vision"
        stream = {"network": "tcp", "security": "tls",
                  "tlsSettings": {"serverName": domain, "fingerprint": "chrome"}}
    elif t == "vless-ws":
        stream = {"network": "ws", "security": "tls",
                  "tlsSettings": {"serverName": domain, "fingerprint": "chrome"},
                  "wsSettings": {"path": "/" + ib["ws_path"], "headers": {"Host": domain}}}
    elif t == "vless-xhttp-reality":
        stream = {"network": "xhttp", "security": "reality",
                  "realitySettings": {"serverName": ib["server_names"][0], "fingerprint": "chrome",
                                      "publicKey": ib["public_key"], "shortId": ib["short_ids"][0]},
                  "xhttpSettings": {"path": "/" + ib["xhttp_path"], "mode": "auto"}}
    elif t == "vless-xhttp-tls":
        stream = {"network": "xhttp", "security": "tls",
                  "tlsSettings": {"serverName": domain, "fingerprint": "chrome"},
                  "xhttpSettings": {"path": "/" + ib["xhttp_path"], "host": domain, "mode": "auto"}}
    port = ib["port"] if t == "vless-xhttp-reality" or ib.get("standalone") else 443
    return {"protocol": "vless", "tag": "proxy",
            "settings": {"vnext": [{"address": host, "port": port, "users": [user]}]},
            "streamSettings": stream}


def full_config(data: dict, ib: dict) -> dict:
    # Local split-tunneling on the CLIENT's own device: "direct" here means
    # "use my own ISP connection, skip the VPS" -- it never touches the
    # server, so it carries none of the server-side IP-exposure risk that
    # `routing.build()` guards against for the country templates.
    rules: list[dict] = [
        {"type": "field", "outboundTag": "direct", "ip": ["geoip:private"]},
    ]
    template = data["routing"].get("template") or "none"
    if template in routing.COUNTRY_MATCHERS:
        dom, ips = routing.COUNTRY_MATCHERS[template]
        if dom:
            rules.append({"type": "field", "outboundTag": "direct", "domain": dom})
        if ips:
            rules.append({"type": "field", "outboundTag": "direct", "ip": ips})
    elif template == "popular":
        rules.append({"type": "field", "outboundTag": "direct",
                      "domain": list(routing.POPULAR_DOMAINS)})
    return {
        "log": {"loglevel": "warning"},
        "inbounds": [
            {"tag": "socks", "port": 10808, "listen": "127.0.0.1", "protocol": "socks",
             "settings": {"udp": True}},
            {"tag": "http", "port": 10809, "listen": "127.0.0.1", "protocol": "http"},
        ],
        "outbounds": [
            _client_outbound(data, ib),
            {"protocol": "freedom", "tag": "direct"},
            {"protocol": "blackhole", "tag": "block"},
        ],
        "routing": {"domainStrategy": "IPIfNonMatch", "rules": rules},
    }


def print_links(data: dict, tag: str | None = None) -> None:
    for ib in data["inbounds"]:
        if tag and ib["tag"] != tag:
            continue
        link = share_link(data, ib)
        print(f"\n=== {ib['tag']} ({ib['type']}) ===")
        if ib["type"] == "turnable":
            print("1) Turnable client (run on the device):")
            print(f"   turnable client -l 127.0.0.1:{TURNABLE_CLIENT_PORT} '{link or '<not available: Turnable is not installed>'}'")
            print("2) Proxy app (v2rayNG, NekoBox, ...), import:")
            print(f"   {turnable_app_link(data, ib)}")
            continue
        print(link)
